service: serverless-deMO

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-01

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
