service: my-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    environment:
      ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${env:AWS_BUCKET_NAME}
      REGION: ${env:AWS_REGION}
      USER_POOL_ID:
        Ref: MyUserPool
      CLIENT_ID:
         Ref: MyUserPoolClient

    events:
      - http:
          path: /random
          method: get
          authorizer:
            name: MyCognitoAuthorizer
            type: COGNITO_USER_POOLS
            identitySource: method.request.header.Authorization
            arn:
              Fn::GetAtt:
                - MyUserPool
                - Arn

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Items
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N  # Assuming "id" is a number
          - AttributeName: author
            AttributeType: S  # Assuming "author" is a string
          - AttributeName: description
            AttributeType: S  # Assuming "description" is a string
          - AttributeName: is_Active
            AttributeType: N  # Assuming "is_Active" is a number
          - AttributeName: is_Deleted
            AttributeType: N  # Assuming "is_Deleted" is a number
          - AttributeName: link_to_file
            AttributeType: S  # Assuming "link_to_file" is a string
          - AttributeName: link_to_Image
            AttributeType: S  # Assuming "link_to_Image" is a string
          - AttributeName: matching_Description
            AttributeType: S  # Assuming "matching_Description" is a string
          - AttributeName: name
            AttributeType: S  # Assuming "name" is a string
          - AttributeName: public
            AttributeType: S  # Assuming "public" is a string
          - AttributeName: type
            AttributeType: S  # Assuming "type" is a string
          - AttributeName: version
            AttributeType: S  # Assuming "version" is a string
          # Add other attributes as needed
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          # Add other key attributes as needed
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: NameIndex
            KeySchema:
              - AttributeName: name
                KeyType: HASH
            Projection:
              ProjectionType: ALL  # Adjust projection type as needed
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

    MyUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: MyUserPool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true

    MyUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: MyUserPoolClient
        UserPoolId:
          Ref: MyUserPool
