service: my-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    environment:
      ACCESS_KEY_ID: `${secrets.AWS_ACCESS_KEY_ID}`
      SECRET_ACCESS_KEY: `${secrets.AWS_SECRET_ACCESS_KEY}`
      BUCKET_NAME: `${secrets.AWS_BUCKET_NAME}`
      REGION: `${secrets.AWS_REGION}`
      # USER_POOL_ID:
      #   Ref: MyUserPool
      # CLIENT_ID:
      #   Ref: MyUserPoolClient
      # Other hardcoded environment variables
    events:
      - http:
          path: /random
          method: get
          authorizer:
            name: MyCognitoAuthorizer
            type: COGNITO_USER_POOLS
            identitySource: method.request.header.Authorization
            arn:
              Fn::GetAtt:
                - MyUserPool
                - Arn

resources:
  Resources:
    MyUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: MyUserPool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true

    MyUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: MyUserPoolClient
        UserPoolId:
          Ref: MyUserPool
        # Add other properties as needed
