service: my-service

provider:
  name: aws
  runtime: nodejs18.x

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    events:
      - http:
          path: /random
          method: get
          authorizer: # Adding Cognito user pool authorizer
            name: MyCognitoAuthorizer
            type: COGNITO_USER_POOLS
            identitySource: method.request.header.Authorization
            arn: 
              Fn::GetAtt:
                - MyUserPool
                - Arn

resources:
  Resources:
    MyUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: MyUserPool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true

plugins:
  - serverless-offline
