service: my-service

provider:
  name: aws
  runtime: nodejs14.x

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    events:
      - http:
          path: /random
          method: get

plugins:
  - serverless-offline
