service: my-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    environment:
      ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${env:AWS_BUCKET_NAME}
      REGION: ${env:AWS_REGION}
      USER_POOL_ID:
        Ref: MyUserPool
      CLIENT_ID:
         Ref: MyUserPoolClient

    events:
      - http:
          path: /random
          method: get
          authorizer:
            name: MyCognitoAuthorizer
            type: COGNITO_USER_POOLS
            identitySource: method.request.header.Authorization
            arn:
              Fn::GetAtt:
                - MyUserPool
                - Arn

resources:
  Resources:
    MyTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "Test-New-Users-Table"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"  # Assuming "id" is a number
          - AttributeName: "Author"
            AttributeType: "S"
          - AttributeName: "Description"
            AttributeType: "S"
          # Add other attribute definitions as needed
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: 'NEW_AND_OLD_IMAGES'

    MyUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: MyUserPool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true

    MyUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: MyUserPoolClient
        UserPoolId:
          Ref: MyUserPool
