name: Deploy register-advertiser Lambda Development
# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - development
    paths:
      - "Dev/**"
jobs:
  deploy_source:
    name: AWS Lambda Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Serverless Framework
        run: npm install -g serverless
        
      - name: Install Serverless Offline
        run: npm install serverless-offline

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install --prefix Dev

      - name: Deploy Lambda function using Serverless Framework
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         REGION: ${{ secrets.AWS_REGION }}
         BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
         USER_POOL_ID:
         Ref: MyUserPool
         CLIENT_ID:Ref: MyUserPoolClient
        run: |
          cd Dev
          sls deploy --access-key-id $ACCESS_KEY_ID --secret-access-key $SECRET_ACCESS_KEY --bucket-name $BUCKET_NAME --client-id $CLIENT_ID --region $REGION --user-pool-id $USER_POOL_ID
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
